a = input('Digite qualquer valor: ')
print('\033[7;31mO tipo primitivo desse valor é\033[m', type(a))
print('\033[0;34mÉ alfabetico:\033[m', a.isalpha())
print('\033[1;35;46mÉ numérico:\033[m', a.isnumeric())
print('É alfanumerico:', a.isalnum())
print('É valor decimal:', a.isdecimal())
print('É minuscullo:', a.islower())
print('É maisculo:', a.isupper())
print('Só tem espaços:', a.isspace())
print('Está capitalizada:', a.istitle())
