fullname = input('Type your full name: ')
upper_ = fullname.upper()
lower_ = fullname.lower()
count_ = len(''.join(fullname.split()))
count_firstn = fullname.split()
print('Your uppercase name is {}'.format(upper_))
print('Your lowercase name is {}'.format(lower_))
print('Your name has {} letters'.format(count_))
print('Your first name is {} and has {} letters'.format(count_firstn[0], len(count_firstn[0])))
